# Generated by Django 3.2.6 on 2021-09-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallacy',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
